# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gareth/Dropbox/Uni/L6/Individual_Project/STM32

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gareth/Dropbox/Uni/L6/Individual_Project/STM32

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gareth/Dropbox/Uni/L6/Individual_Project/STM32/CMakeFiles /home/gareth/Dropbox/Uni/L6/Individual_Project/STM32//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gareth/Dropbox/Uni/L6/Individual_Project/STM32/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ElectronicLoad.elf

# Build rule for target.
ElectronicLoad.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ElectronicLoad.elf
.PHONY : ElectronicLoad.elf

# fast build rule for target.
ElectronicLoad.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/build
.PHONY : ElectronicLoad.elf/fast

Src/clock_tree.obj: Src/clock_tree.c.obj

.PHONY : Src/clock_tree.obj

# target to build an object file
Src/clock_tree.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/clock_tree.c.obj
.PHONY : Src/clock_tree.c.obj

Src/clock_tree.i: Src/clock_tree.c.i

.PHONY : Src/clock_tree.i

# target to preprocess a source file
Src/clock_tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/clock_tree.c.i
.PHONY : Src/clock_tree.c.i

Src/clock_tree.s: Src/clock_tree.c.s

.PHONY : Src/clock_tree.s

# target to generate assembly for a file
Src/clock_tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/clock_tree.c.s
.PHONY : Src/clock_tree.c.s

Src/gpio.obj: Src/gpio.c.obj

.PHONY : Src/gpio.obj

# target to build an object file
Src/gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/gpio.c.obj
.PHONY : Src/gpio.c.obj

Src/gpio.i: Src/gpio.c.i

.PHONY : Src/gpio.i

# target to preprocess a source file
Src/gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/gpio.c.i
.PHONY : Src/gpio.c.i

Src/gpio.s: Src/gpio.c.s

.PHONY : Src/gpio.s

# target to generate assembly for a file
Src/gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/gpio.c.s
.PHONY : Src/gpio.c.s

Src/init.obj: Src/init.c.obj

.PHONY : Src/init.obj

# target to build an object file
Src/init.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/init.c.obj
.PHONY : Src/init.c.obj

Src/init.i: Src/init.c.i

.PHONY : Src/init.i

# target to preprocess a source file
Src/init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/init.c.i
.PHONY : Src/init.c.i

Src/init.s: Src/init.c.s

.PHONY : Src/init.s

# target to generate assembly for a file
Src/init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/init.c.s
.PHONY : Src/init.c.s

Src/main.obj: Src/main.c.obj

.PHONY : Src/main.obj

# target to build an object file
Src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/main.c.obj
.PHONY : Src/main.c.obj

Src/main.i: Src/main.c.i

.PHONY : Src/main.i

# target to preprocess a source file
Src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/main.c.i
.PHONY : Src/main.c.i

Src/main.s: Src/main.c.s

.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/main.c.s
.PHONY : Src/main.c.s

Src/system_stm32g0xx.obj: Src/system_stm32g0xx.c.obj

.PHONY : Src/system_stm32g0xx.obj

# target to build an object file
Src/system_stm32g0xx.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/system_stm32g0xx.c.obj
.PHONY : Src/system_stm32g0xx.c.obj

Src/system_stm32g0xx.i: Src/system_stm32g0xx.c.i

.PHONY : Src/system_stm32g0xx.i

# target to preprocess a source file
Src/system_stm32g0xx.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/system_stm32g0xx.c.i
.PHONY : Src/system_stm32g0xx.c.i

Src/system_stm32g0xx.s: Src/system_stm32g0xx.c.s

.PHONY : Src/system_stm32g0xx.s

# target to generate assembly for a file
Src/system_stm32g0xx.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Src/system_stm32g0xx.c.s
.PHONY : Src/system_stm32g0xx.c.s

Startup/startup_stm32g071xx.obj: Startup/startup_stm32g071xx.s.obj

.PHONY : Startup/startup_stm32g071xx.obj

# target to build an object file
Startup/startup_stm32g071xx.s.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/Startup/startup_stm32g071xx.s.obj
.PHONY : Startup/startup_stm32g071xx.s.obj

home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.obj: home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.c.obj

.PHONY : home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.obj

# target to build an object file
home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.c.obj
.PHONY : home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.c.obj

home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.i: home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.c.i

.PHONY : home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.i

# target to preprocess a source file
home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.c.i
.PHONY : home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.c.i

home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.s: home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.c.s

.PHONY : home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.s

# target to generate assembly for a file
home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronicLoad.elf.dir/build.make CMakeFiles/ElectronicLoad.elf.dir/home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.c.s
.PHONY : home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ElectronicLoad.elf"
	@echo "... Src/clock_tree.obj"
	@echo "... Src/clock_tree.i"
	@echo "... Src/clock_tree.s"
	@echo "... Src/gpio.obj"
	@echo "... Src/gpio.i"
	@echo "... Src/gpio.s"
	@echo "... Src/init.obj"
	@echo "... Src/init.i"
	@echo "... Src/init.s"
	@echo "... Src/main.obj"
	@echo "... Src/main.i"
	@echo "... Src/main.s"
	@echo "... Src/system_stm32g0xx.obj"
	@echo "... Src/system_stm32g0xx.i"
	@echo "... Src/system_stm32g0xx.s"
	@echo "... Startup/startup_stm32g071xx.obj"
	@echo "... home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.obj"
	@echo "... home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.i"
	@echo "... home/gareth/Documents/Electronics/Libraries/ST7066U_LCD/st7066u_lcd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

