/* Electronic Load Project 
 * Gareth Waymark up762102
 * 
 * GPIO configuration functions
 */

#include "gpio.h"
static void configureGPIOA(void);
static void configureGPIOB(void);

void init_gpio(void)
{
    configureGPIOA();
    configureGPIOB();
}

static void configureGPIOA(void)
{
    /* Configure GPIOA pins */
    MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODE4, GPIO_MODER_MODE4_0); // PA4 OUTPUT
    MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODE2, GPIO_MODER_MODE2_0); // PA2 OUTPUT
}

static void configureGPIOB(void)
{
    /* Configure LCD control pins. Open drain, 5V tolerent */
    /* EN */
    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE3, GPIO_MODER_MODE3_0);
    SET_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT3);
    MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED3, GPIO_OSPEEDR_OSPEED3_0);
    
    /* RW */
    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE4, GPIO_MODER_MODE4_0);
    SET_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT4);
    MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED4, GPIO_OSPEEDR_OSPEED4_0);
    
    /* RS */
    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE5, GPIO_MODER_MODE5_0);
    SET_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT5);
    MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED5, GPIO_OSPEEDR_OSPEED5_0);
    
    /* D4 */
    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE6, GPIO_MODER_MODE6_0);
    SET_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT6);
    MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED6, GPIO_OSPEEDR_OSPEED6_0);
    
    /* D5 */
    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE7, GPIO_MODER_MODE7_0);
    SET_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT7);
    MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED7, GPIO_OSPEEDR_OSPEED7_0);
    
    /* D6 */
    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE8, GPIO_MODER_MODE8_0);
    SET_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT8);
    MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED8, GPIO_OSPEEDR_OSPEED8_0);
    
    /* D7 */
    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE9, GPIO_MODER_MODE9_0);
    SET_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT9);
    MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED9, GPIO_OSPEEDR_OSPEED9_0);
}
